--create database case_study2;
use case_study2;

select * from CUSTOMER
select * from TRANSACTIONS
select * from PROD_CAT_INFO

/*DATA PREPERATION AND UNDERSTANDING*/
/*1. What is the total number of rows in each of the 3 tables in the database? */

select 'Customer' as [TBL_NAME], count(*) as [ROW_CNT] from Customer
UNION ALL
select 'Transactions' as [TBL_NAME], count(*) as [ROW_CNT] from Transactions
UNION ALL
select 'prod_cat_info' as [TBL_NAME], count(*) as [ROW_CNT] from prod_cat_info;

/*2. What is the total number of transactions that have a return? */
select count(*) from Transactions where Qty like '%-%' AND total_amt like '%-%'

/*3. As you would have noticed, the dates provided across the datasets are not in a
correct format. As first steps, pls convert the date variables into valid date formats
before proceeding ahead. */

select CONVERT(DATE, DOB, 105) from Customer;
select CONVERT(DATE, tran_date, 105) from Transactions;


/*4. What is the time range of the transaction data available for analysis? Show the
output in number of days, months and years simultaneously in different columns. */

select DATEDIFF(DAY, (MIN(TRAN_DATE)), (MAX(TRAN_DATE))) as [DAYS], 
DATEDIFF(MONTH, (MIN(TRAN_DATE)), (MAX(TRAN_DATE))) as [MONTHS],
DATEDIFF(YEAR, (MIN(TRAN_DATE)), (MAX(TRAN_DATE))) as [YEAR]
from Transactions

/*5. Which product category does the sub-category “DIY” belong to? */

select distinct prod_cat, prod_subcat from prod_cat_info where prod_subcat = 'DIY'


/*DATA ANALYSIS*/

/*1. Which channel is most frequently used for transactions?*/

select TOP 1 Store_type, count(Store_type)  as [Ttl_Tran] from Transactions 
group by Store_type
order by Ttl_Tran DESC;

/*2. What is the count of Male and Female customers in the database? */

select GENDER, count(customer_Id) as [Ttl_Cus]
from Customer where GENDER IS NOT NULL group by GENDER

/*3. From which city do we have the maximum number of customers and how many? */

select TOP 1 city_code, count(customer_Id) as [Ttl_Cus]
from Customer 
group by city_code
order by Ttl_Cus desc;

/*4. How many sub-categories are there under the Books category? */

select prod_cat, COUNT(prod_subcat) 
from prod_cat_info where prod_cat = 'Books'
group by prod_cat;

/*5. What is the maximum quantity of products ever ordered? */

select MAX(QTY) from Transactions where QTY not like '-%'

/*6. What is the net total revenue generated in categories Electronics and Books? */

select SUM(total_amt)
from Transactions A
INNER JOIN prod_cat_info B on A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
where B.prod_cat IN ('Electronics', 'Books')

select B.prod_cat, SUM(total_amt)
from Transactions A
INNER JOIN prod_cat_info B on A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
where B.prod_cat IN ('Electronics', 'Books')
group by prod_cat

/*7. How many customers have >10 transactions with us, excluding returns? */

select count(*) from
(select cust_id, count(transaction_id) as [Ttl_Cus] from Transactions 
group by cust_id
having count(transaction_id) > 10)E;

/*8. What is the combined revenue earned from the “Electronics” & “Clothing”
categories, from “Flagship stores”?*/

select A.Store_type, SUM(total_amt) as [Ttl_Revenue]
from Transactions A
INNER JOIN prod_cat_info B on A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
where B.prod_cat IN ('Electronics', 'Clothing') AND A.Store_type in ('Flagship store')
group by A.Store_type

/*9. What is the total revenue generated from “Male” customers in “Electronics”
category? Output should display total revenue by prod sub-cat. */

select A.Gender, SUM(B.total_amt)
from Customer A
INNER JOIN Transactions B on A.customer_Id = B.cust_id
INNER JOIN prod_cat_info C on B.prod_cat_code = C.prod_cat_code AND B.prod_subcat_code = C.prod_sub_cat_code
where A.Gender IN ('M') AND C.prod_cat IN ('Electronics')
group by A.Gender

/*10.What is percentage of sales and returns by product sub category; display only top
5 sub categories in terms of sales? */

select TOP 5 B.prod_subcat,
(SUM(total_amt)/(select SUM(total_amt) from Transactions)) * 100 as [% SALES],
(COUNT(CASE WHEN Qty < 0 THEN QTY ELSE NULL END)/SUM(QTY)) * 100 as [% RETURNS]
from Transactions A
INNER JOIN prod_cat_info B on A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
group by B.prod_subcat
order by [% SALES] DESC;

/*11. For all customers aged between 25 to 35 years find what is the net total revenue
generated by these consumers in last 30 days of transactions from max transaction
date available in the data? */

select cust_id, SUM(total_amt)
from Transactions
where cust_id IN
				(
				select customer_Id 
				from Customer
				where DATEDIFF(YEAR, DOB, GETDATE()) BETWEEN 25 AND 35
				)
AND tran_date BETWEEN DATEADD(DAY, -30, (select max(tran_date) from Transactions)) AND (select MAX(tran_date) from Transactions)
group by cust_id
					

/*12.	Which product category has seen the max value of returns in the last 3 
months of transactions?*/

select TOP 1 B.prod_cat, SUM(total_amt) as [Ttl_RTN]
from Transactions A
INNER JOIN prod_cat_info B on A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
WHERE tran_date BETWEEN DATEADD(MONTH, -3, (select max(tran_date) from Transactions)) AND (select MAX(tran_date) from Transactions)
AND total_amt LIKE '-%'
group by B.prod_cat
order by Ttl_RTN DESC


/*13.Which store-type sells the maximum products; by value of sales amount and by
quantity sold? */

--Solution 1: Using TOP Clause
select TOP 1 Store_type, SUM(total_amt) as [Ttl_SALES], SUM(Qty) as [QTY] 
from Transactions
group by Store_type
order by Ttl_SALES DESC

--Solution 2: Using HAVING CLAUSE with ALL Keyword
select Store_type, SUM(total_amt) as [Ttl_SALES], SUM(Qty) as [QTY] 
from Transactions
group by Store_type
HAVING SUM(TOTAL_AMT) >=ALL (SELECT SUM(TOTAL_AMT) FROM Transactions GROUP BY STORE_TYPE)
AND SUM(QTY) >=ALL (SELECT SUM(QTY) FROM Transactions GROUP BY STORE_TYPE)
order by Ttl_SALES DESC


/*14.What are the categories for which average revenue is above the overall average. */

select B.prod_cat, AVG(total_amt) as [AVG_REV]
from Transactions A
INNER JOIN prod_cat_info B on A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
group by B.prod_cat
HAVING AVG(total_amt) > (select AVG(total_amt) from Transactions)


/*15. Find the average and total revenue by each subcategory for the categories which
are among top 5 categories in terms of quantity sold. */

select B.prod_cat, B.prod_subcat, AVG(total_amt) as [AVG_REV], SUM(total_amt) as [Ttl_REV], SUM(Qty)
from Transactions A
INNER JOIN prod_cat_info B on A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
where prod_cat IN 
				(
				select top 5 B.prod_cat
				from Transactions A
				INNER JOIN prod_cat_info B on A.prod_cat_code = B.prod_cat_code AND A.prod_subcat_code = B.prod_sub_cat_code
				group by B.prod_cat
				order by SUM(Qty) DESC
				)
group by B.prod_cat, B.prod_subcat



